# Generated by Django 5.0 on 2024-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='name_en_us',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='new',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='new',
            name='news_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='news_ru',
            field=models.TextField(null=True),
        ),
    ]
